### ISSUE TITLE
Sends all categories ignoring selection

### ISSUE THREAD

**Issue by ghost** [pichalite/nodebb-plugin-slack-extended#1]
Great plugin!!!  The only issue I have is that it is sending every post in every category.  We have some categories that we don't want to be propagated.

**Comment by pichalite** [comment]
You can select the categories you want in the plugin's ACP settings page.

**Comment by ghost** [comment]
I know.  I did that, but it still sends all the posts regardless.

**Comment by ghost** [comment]
Hold up, found another error
