### ISSUE TITLE
Slack plugin as pushbullet replacement

### ISSUE THREAD

**Issue by henrikekblad** [pichalite/nodebb-plugin-slack-extended#4]
Hi, 

Would it be possible to  use this plugin like the pushbullet plugin? 

We got a pretty active forum and since pushbullet introduced their monthly 500 message limit slack seems to be the obvious replacement for pushing notification messages.  

Guess it would require a per user api token configuration option (like nodebb-plugin-pushbullet has).

**Comment by pichalite** [comment]
That would require every user to setup their own team, add integration and update them in settings. Too complicated from the user perspective.
