### ISSUE TITLE
Option to notify only of new threads?

### ISSUE THREAD

**Issue by Xseba360** [pichalite/nodebb-plugin-slack-extended#5]
Hey. Is there a chance of making an option to notify only of the newly created threads, and not the replies?

**Comment by pichalite** [comment]
The NodeBB hook used by this plugin doesn't identify if it's a new topic or a reply.

**Comment by pichalite** [comment]
https://github.com/NodeBB/NodeBB/pull/5376

**Comment by pichalite** [comment]
Use v0.0.8

requires NodeBB v1.4.3
