### ISSUE TITLE
How to set this up?

### ISSUE THREAD

**Issue by aevans1987** [pichalite/nodebb-plugin-slack-extended#6]
I've seen the readme.md that explains to setup an incoming webhook, however as near as i can tell, the directions on Webhook is out of date as i am not given a domain and token when i setup an incoming webhook.

I am given a URL to send to. See below for what the Incoming Webhook setup looks like:

![image](https://cloud.githubusercontent.com/assets/23514631/22960544/910c9896-f30c-11e6-8047-11fecc7116ac.png)

**Comment by pichalite** [comment]
@Jacob-Evans updated readme. All you need is the Webhook URL and channel.
